"use server";

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Byuk5d4Rq7d
 */
import Link from "next/link"
import Image from "next/image"

export async function Landing() {
  return (
    <section className="w-full py-12 md:py-24 lg:py-32">
      <div className="container space-y-12 px-4 md:px-6">
        <div className="flex flex-col items-center justify-center space-y-4 text-center">
          <div className="space-y-2">
            <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">
              For Playlist Lovers
            </div>
            <h1 className="text-4xl font-bold tracking-tighter sm:text-6xl">Curate with Confidence</h1>
            <p className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              Manage your playlists with ease. Share the joy of discovery with friends. Let everyone contribute while
              you stay in control.
            </p>
          </div>
          <Image
            alt="Image"
            className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full"
            height="450"
            src="/placeholder.svg"
            width="800"
          />
        </div>
        <div className="mx-auto grid max-w-sm items-start gap-8 sm:max-w-4xl sm:grid-cols-2 md:gap-12 lg:max-w-5xl lg:grid-cols-3">
          <div className="grid gap-1">
            <h3 className="text-lg font-bold">Collaborative Curation</h3>
            <p className="text-sm text-gray-500 dark:text-gray-400">
              Let everyone add their favorite tracks to the playlist.
            </p>
          </div>
          <div className="grid gap-1">
            <h3 className="text-lg font-bold">Approval Workflow</h3>
            <p className="text-sm text-gray-500 dark:text-gray-400">
              Set the number of votes required before a track is added.
            </p>
          </div>
          <div className="grid gap-1">
            <h3 className="text-lg font-bold">Shared Playlists</h3>
            <p className="text-sm text-gray-500 dark:text-gray-400">
              Create a space for your community to share music.
            </p>
          </div>
        </div>
        <div className="flex flex-col gap-2 min-[400px]:flex-row justify-center">
          <Link
            className="inline-flex h-10 items-center justify-center rounded-md bg-gray-900 px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
            href="/manage"
          >
            Get Started
          </Link>
        </div>
      </div>
    </section>
  )
}
