/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/NW5MslhUPSm
 */
import { Button } from "@/components/ui/button"
import { AvatarImage, Avatar } from "@/components/ui/avatar"
import { ScrollArea } from "@/components/ui/scroll-area"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"
import Image from "next/image"

export function PlaylistManager() {
  return (
    <div className="flex h-screen dark:bg-[#121212] dark:text-white">
      <nav className="w-60 flex flex-col dark:bg-[#000] p-4 space-y-4">
        <div className="flex items-center justify-between">
          <h2 className="text-xs font-semibold uppercase tracking-wider">Your Playlists</h2>
          <div className="flex space-x-1">
            <Button variant="ghost">
              <PlusIcon className="w-4 h-4" />
            </Button>
          </div>
        </div>
        <ScrollArea className="mt-4 space-y-2 flex-1">
          <Button className="flex items-center space-x-2" variant="ghost">
            <Avatar>
              <AvatarImage alt="Playlist" src="/placeholder.svg?height=20&width=20" />
            </Avatar>
            <span className="text-sm">house dance mix thursday morning</span>
          </Button>
        </ScrollArea>
      </nav>
      <main className="flex-1 overflow-y-auto">
        <div className="relative">
          <Image
            alt="Playlist cover"
            className="w-full h-72 object-cover"
            height="300"
            src="/placeholder.svg"
            style={{
              aspectRatio: "1360/300",
              objectFit: "cover",
            }}
            width="1360"
          />
          <div className="absolute inset-0 bg-gradient-to-t from-[#121212] to-transparent" />
          <div className="absolute bottom-0 p-8">
            <h1 className="text-4xl font-bold text-white">house dance mix thursday morning</h1>
            <p className="text-sm mt-2 text-white">
              You listened to electronic music and beats on Thursday mornings. Here&apos;s some: electronic, ibiza, beats,
              pop edm, club, and heatwave
            </p>
            <p className="text-xs mt-1 text-gray-300">Made for Luke • 50 songs, 2 hr 59 min • Next update at 2:36 PM</p>
          </div>
        </div>
        <div className="px-8 py-4">
          <div className="mt-6">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead className="w-12">#</TableHead>
                  <TableHead>Title</TableHead>
                  <TableHead>Album</TableHead>
                  <TableHead className="w-24">Time</TableHead>
                  <TableHead className="w-12" />
                </TableRow>
              </TableHeader>
              <TableBody>
                <TableRow>
                  <TableCell>1</TableCell>
                  <TableCell>The Fall</TableCell>
                  <TableCell>So Far So Good</TableCell>
                  <TableCell>3:16</TableCell>
                  <TableCell>
                    <Button className="hover:bg-[#121212]" variant="ghost">
                      <TrashIcon className="w-6 h-6" />
                    </Button>
                  </TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </div>
        </div>
      </main>
    </div>
  )
}


function PlusIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}


function TrashIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 6h18" />
      <path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6" />
      <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2" />
    </svg>
  )
}
